const express = require('express');
const { protect } = require('../middleware/authmiddleware')
const router =  express.Router();
const { registerUser, getMeUser, loginUser } = require('../controllers/userController')

router.post('/', registerUser)
router.post('/login', loginUser);
router.post('/me', protect, getMeUser);

module.exports = router;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     